const transports=[
 {id:'TR-2026-0718',client:'Nordic Freight AB',from:'Oslo, NO',to:'Göteborg, SE',driver:'Adam Nowak',truck:'ZS 8412K',progress:74,left:'128 km',eta:'Dzisiaj, 12:40',status:'W trasie',tone:'blue'},
 {id:'TR-2026-0719',client:'ScanLogistics AS',from:'Stockholm, SE',to:'Bergen, NO',driver:'Tomasz Lis',truck:'ZS 2209P',progress:46,left:'492 km',eta:'Dzisiaj, 18:20',status:'Ryzyko opóźnienia',tone:'red'},
 {id:'TR-2026-0720',client:'Baltic Cargo',from:'Malmö, SE',to:'Aarhus, DK',driver:'Piotr Wójcik',truck:'ZS 7731M',progress:82,left:'96 km',eta:'Dzisiaj, 10:55',status:'W trasie',tone:'blue'},
 {id:'TR-2026-0721',client:'Norway Express',from:'Kristiansand, NO',to:'Oslo, NO',driver:'Karol Maj',truck:'ZS 4421R',progress:21,left:'248 km',eta:'Dzisiaj, 15:30',status:'Postój',tone:'amber'},
 {id:'TR-2026-0722',client:'Svea Transport',from:'Helsingborg, SE',to:'Uppsala, SE',driver:'Michał Kot',truck:'ZS 1190T',progress:55,left:'284 km',eta:'Dzisiaj, 17:10',status:'W trasie',tone:'blue'},
 {id:'TR-2026-0723',client:'NordCargo',from:'Gothenburg, SE',to:'Trondheim, NO',driver:'Jan Kurek',truck:'ZS 9088W',progress:31,left:'602 km',eta:'Jutro, 08:00',status:'W trasie',tone:'blue'}
];
const fleet=[
 {truck:'ZS 8412K',driver:'Adam Nowak',state:'W trasie',km:'412 km',speed:'76 km/h',gps:'1 min temu'},
 {truck:'ZS 2209P',driver:'Tomasz Lis',state:'Uwaga',km:'368 km',speed:'0 km/h',gps:'12 min temu'},
 {truck:'ZS 7731M',driver:'Piotr Wójcik',state:'W trasie',km:'501 km',speed:'82 km/h',gps:'2 min temu'},
 {truck:'ZS 4421R',driver:'Karol Maj',state:'Postój',km:'219 km',speed:'0 km/h',gps:'4 min temu'},
 {truck:'ZS 1190T',driver:'Michał Kot',state:'W trasie',km:'447 km',speed:'71 km/h',gps:'1 min temu'},
 {truck:'ZS 9088W',driver:'Jan Kurek',state:'W trasie',km:'390 km',speed:'79 km/h',gps:'3 min temu'}
];
const drivers=[
 {name:'Adam Nowak',phone:'+48 501 220 101',email:'adam@firma.pl',license:'SZA/10293',until:'2029-04-18',status:'W trasie'},
 {name:'Tomasz Lis',phone:'+48 501 220 102',email:'tomasz@firma.pl',license:'SZB/28411',until:'2028-11-02',status:'W trasie'},
 {name:'Piotr Wójcik',phone:'+48 501 220 103',email:'piotr@firma.pl',license:'SZC/14820',until:'2030-01-16',status:'W trasie'},
 {name:'Karol Maj',phone:'+48 501 220 104',email:'karol@firma.pl',license:'SZD/30125',until:'2027-08-30',status:'Postój'},
 {name:'Michał Kot',phone:'+48 501 220 105',email:'michal@firma.pl',license:'SZE/22109',until:'2029-06-12',status:'W trasie'},
 {name:'Jan Kurek',phone:'+48 501 220 106',email:'jan@firma.pl',license:'SZF/19877',until:'2028-03-22',status:'W trasie'}
];
const initials=n=>n.split(' ').map(x=>x[0]).join('');
function renderTable(list=transports.slice(0,4)){
 document.querySelector('#transportTableBody').innerHTML=list.map(t=>`<tr class="transport-row" data-id="${t.id}"><td><strong>${t.id}</strong><small>${t.client}</small></td><td><div class="route-cell"><span class="route-line"><i></i><span></span><i></i></span><div><strong>${t.from}</strong><small>${t.to}</small></div></div></td><td><div class="driver-cell"><span class="mini-avatar">${initials(t.driver)}</span><div><strong>${t.driver}</strong><small>${t.truck}</small></div></div></td><td><div class="progress-wrap"><div class="progress-meta"><span>${t.progress}%</span><span>${t.left}</span></div><div class="progress"><i style="width:${t.progress}%"></i></div></div></td><td><strong>${t.eta.split(',')[0]}</strong><small>${t.eta.split(',')[1]||''}</small></td><td><span class="badge ${t.tone}">${t.status}</span></td><td><button class="more-btn">•••</button></td></tr>`).join('');
 bindRows();
}
function renderCards(){document.querySelector('#transportCards').innerHTML=transports.map(t=>`<article class="panel transport-card transport-row" data-id="${t.id}"><div class="transport-card-head"><div><h3>${t.id}</h3><p>${t.client}</p></div><span class="badge ${t.tone}">${t.status}</span></div><div class="route-display"><div><b>${t.from.split(',')[0]}</b><span>${t.from.split(',')[1]}</span></div><span>···· ✈ ····</span><div><b>${t.to.split(',')[0]}</b><span>${t.to.split(',')[1]}</span></div></div><div class="progress-meta"><span>Postęp ${t.progress}%</span><span>${t.left} do celu</span></div><div class="progress"><i style="width:${t.progress}%"></i></div><div class="card-footer" style="margin-top:14px"><span class="mini-avatar">${initials(t.driver)}</span><div style="margin-left:8px"><b>${t.driver}</b><span style="display:block">${t.truck}</span></div><div style="text-align:right"><span>ETA</span><b style="display:block">${t.eta}</b></div></div></article>`).join('');bindRows()}
function renderFleet(){document.querySelector('#fleetGrid').innerHTML=fleet.map(f=>`<article class="fleet-card"><div class="fleet-card-head"><div><h3>${f.truck}</h3><p>Volvo FH 500</p></div><span class="badge ${f.state==='W trasie'?'green':f.state==='Uwaga'?'red':'amber'} fleet-status">${f.state}</span></div><div class="vehicle-illustration">▰</div><div class="driver-cell"><span class="mini-avatar">${initials(f.driver)}</span><div><strong>${f.driver}</strong><small>Kierowca</small></div></div><div class="fleet-stats"><div><span>Dzisiaj</span><b>${f.km}</b></div><div><span>Prędkość</span><b>${f.speed}</b></div><div><span>GPS</span><b>${f.gps}</b></div></div></article>`).join('')}
function renderFleetManagement(){document.querySelector('#driversCount').textContent=drivers.length;document.querySelector('#vehiclesCount').textContent=fleet.length;document.querySelector('#driversTable').innerHTML=`<div class="management-head"><span>KIEROWCA</span><span>KONTAKT</span><span>PRAWO JAZDY</span><span>STATUS</span><span></span></div>${drivers.map(d=>`<div class="management-row"><div class="entity-cell"><span class="mini-avatar">${initials(d.name)}</span><section><b>${d.name}</b><small>ID: DR-${String(drivers.indexOf(d)+1).padStart(3,'0')}</small></section></div><div><b>${d.phone}</b><small>${d.email||'Brak e-maila'}</small></div><div><b>${d.license}</b><small>ważne do ${d.until}</small></div><span><i class="entity-status ${d.status==='Nieaktywny'?'off':''}"></i>${d.status}</span><button class="more-btn">•••</button></div>`).join('')}`;document.querySelector('#vehiclesTable').innerHTML=`<div class="management-head vehicle-columns"><span>POJAZD</span><span>KIEROWCA</span><span>DANE GPS</span><span>STATUS</span><span></span></div>${fleet.map((f,i)=>`<div class="management-row vehicle-columns"><div class="entity-cell"><span class="vehicle-mini">▰</span><section><b>${f.truck}</b><small>${f.model||'Volvo FH 500'} · ${f.year||'2022'}</small></section></div><div><b>${f.driver}</b><small>${f.driver==='Nie przypisano'?'Wymaga przypisania':'Przypisany kierowca'}</small></div><div><b>${f.gpsConnected===false?'Do podłączenia':'Połączony'}</b><small>${f.gpsConnected===false?'Brak identyfikatora':f.gps}</small></div><span><i class="entity-status ${f.state==='Nieaktywny'?'off':''}"></i>${f.state}</span><button class="more-btn">•••</button></div>`).join('')}`;const select=document.querySelector('#transportForm select[name="driver"]');const selected=select.value;select.innerHTML=`<option>Nie przypisano</option>${drivers.filter(d=>d.status!=='Nieaktywny').map(d=>`<option>${d.name}</option>`).join('')}`;if([...select.options].some(o=>o.value===selected))select.value=selected}
function renderTimeline(){document.querySelector('#timelineRows').innerHTML=fleet.slice(0,4).map((f,i)=>`<div class="timeline-row"><div class="timeline-person"><span class="mini-avatar">${initials(f.driver)}</span><div><strong>${f.driver}</strong><small>${f.truck}</small></div></div><div class="timeline-track"><div class="timeline-job ${['job-blue','job-orange','job-green','job-blue'][i]}" style="left:${[3,18,7,31][i]}%;width:${[54,47,68,49][i]}%"><b>${transports[i].from.split(',')[0]} → ${transports[i].to.split(',')[0]}</b>${transports[i].id}</div></div></div>`).join('')}
function renderReports(){const t=transports[0];document.querySelector('#reportsWorkspace').innerHTML=`<div class="report-sidebar">${transports.slice(0,4).map((x,i)=>`<div class="report-select ${i===0?'active':''}" data-report="${x.id}"><h4>${x.client}</h4><p>${x.id} · ${x.to}</p><span class="badge ${x.tone==='red'?'amber':'green'}">${x.tone==='red'?'Wymaga sprawdzenia':'Gotowy'}</span></div>`).join('')}</div><div class="email-preview"><span class="eyebrow">WERSJA ROBOCZA WIADOMOŚCI</span><label><span>Do:</span><input value="operations@nordicfreight.se"></label><label><span>Temat:</span><input value="Transport update · ${t.id}"></label><div class="email-body" contenteditable="true">Good morning,<br><br>The vehicle carrying shipment <strong>${t.id}</strong> is currently on the route from ${t.from} to ${t.to}. The vehicle has completed ${t.progress}% of the route and is approximately <strong>${t.left}</strong> from the delivery location.<br><br>Estimated arrival: <strong>${t.eta}</strong>. The delivery remains on schedule. We will inform you if the situation changes.<br><br>Best regards,<br>Logistics Team</div><div class="email-actions"><button class="secondary-btn">Kopiuj treść</button><button class="primary-btn send-draft">Utwórz draft e-mail</button></div></div>`;document.querySelector('.send-draft').onclick=()=>showToast('Draft został przygotowany','Wiadomość oczekuje na wysłanie.')}
function bindRows(){document.querySelectorAll('.transport-row').forEach(row=>row.onclick=()=>openTransport(row.dataset.id))}
function openTransport(id){const t=transports.find(x=>x.id===id);if(!t)return;document.querySelector('#drawerContent').innerHTML=`<div class="drawer-header"><span class="eyebrow">${t.id}</span><h2>${t.client}</h2><p>Aktywny transport · dane z aplikacji GPS</p></div><span class="badge ${t.tone}">${t.status}</span><div class="drawer-route"><div><i></i><section><small>ZAŁADUNEK</small><b>${t.from}</b></section></div><span></span><div><i></i><section><small>ROZŁADUNEK</small><b>${t.to}</b></section></div></div><div class="drawer-section"><h3>Realizacja</h3><div class="progress-meta"><span>${t.progress}% trasy</span><span>${t.left} do celu</span></div><div class="progress"><i style="width:${t.progress}%"></i></div></div><div class="drawer-section"><h3>Zasoby</h3><div class="drawer-grid"><div><span>Kierowca</span><b>${t.driver}</b></div><div><span>Ciągnik</span><b>${t.truck}</b></div><div><span>Naczepa</span><b>N-${Math.ceil(Math.random()*20).toString().padStart(2,'0')}</b></div><div><span>Planowane ETA</span><b>${t.eta}</b></div></div></div><div class="drawer-section"><h3>Ostatnia pozycja GPS</h3><p>Okolice Jönköping, E4 · zaktualizowano 2 min temu</p></div><button class="primary-btn full">Przygotuj raport dla klienta</button>`;document.querySelector('#detailDrawer').classList.add('open');document.querySelector('#drawerBackdrop').classList.add('open')}
function closeDrawer(){document.querySelector('#detailDrawer').classList.remove('open');document.querySelector('#drawerBackdrop').classList.remove('open')}
const titles={dashboard:'Dzień dobry, Marek',transports:'Transporty',planner:'Planer tras',fleet:'Flota i kierowcy',reports:'Raporty',inbox:'Skrzynka zleceń',kilometers:'Kilometry',fuel:'Paliwo i marża',settlements:'Rozliczenia',settings:'Ustawienia'};
function getSessionUser(){try{return JSON.parse(sessionStorage.getItem('lm_session')||localStorage.getItem('lm_session')||'null')}catch{return null}}
function switchView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#${name}View`)?.classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));const sessionUser=getSessionUser();document.querySelector('#pageTitle').textContent=name==='dashboard'?`Dzień dobry, ${sessionUser?.firstName||'Marek'}`:(titles[name]||'Logistic Master');document.querySelector('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view));document.querySelectorAll('[data-view-jump]').forEach(n=>n.onclick=()=>switchView(n.dataset.viewJump));
document.querySelector('#mobileMenu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');
const modal=document.querySelector('#transportModal');document.querySelector('#newTransportBtn').onclick=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')};document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});
const sampleMail=`Temat: New transport order 84721 / Malmö - Oslo

Good morning,
please arrange transport for Nordic Freight AB.
Loading: Malmö, Sweden, 21.07.2026 between 08:00-09:00.
Delivery: Oslo, Norway, no later than 21.07.2026 at 18:30.
Reference number: NF-84721.
Cargo: 24 pallets, 18,400 kg. Please report vehicle position in the morning.
Best regards, Anna`;
const aiPanel=document.querySelector('#aiImportPanel');
document.querySelector('#aiImportBtn').onclick=()=>{aiPanel.classList.toggle('open');if(aiPanel.classList.contains('open'))document.querySelector('#emailSource').focus()};
document.querySelector('#useSampleMail').onclick=()=>{document.querySelector('#emailSource').value=sampleMail};
document.querySelector('#showSourceBtn').onclick=()=>{aiPanel.classList.add('open');document.querySelector('#emailSource').scrollIntoView({behavior:'smooth',block:'center'})};
document.querySelector('#analyzeEmailBtn').onclick=()=>{const source=document.querySelector('#emailSource').value.trim();if(!source){showToast('Brakuje treści wiadomości','Wklej maila, który mamy przeanalizować.');return}const btn=document.querySelector('#analyzeEmailBtn');btn.disabled=true;btn.textContent='✦ Analizuję…';setTimeout(()=>{const form=document.querySelector('#transportForm');form.elements.number.value='NF-84721';form.elements.client.value='Nordic Freight AB';form.elements.from.value='Malmö, SE';form.elements.to.value='Oslo, NO';form.elements.date.value='2026-07-21T18:30';form.elements.notes.value='Załadunek 08:00–09:00 · 24 palety · 18 400 kg · wymagany raport poranny';document.querySelectorAll('.confidence').forEach(c=>{c.classList.add('show');const medium=c.dataset.confidence==='notes';c.classList.add(medium?'medium':'high');c.textContent=medium?'82% — sprawdź':'98% pewności';c.closest('label').classList.toggle('field-highlight',medium)});document.querySelector('#extractionResult').classList.add('show');aiPanel.classList.remove('open');btn.disabled=false;btn.textContent='✦ Analizuj wiadomość';showToast('AI odczytało zlecenie','Sprawdź uzupełnione pola przed zatwierdzeniem.');},850)};
document.querySelector('#transportForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));transports.unshift({id:d.number,client:d.client,from:d.from,to:d.to,driver:d.driver,truck:'Do przypisania',progress:0,left:'—',eta:d.date.replace('T',' '),status:'Nowy',tone:'green'});renderTable();renderCards();modal.classList.remove('open');showToast('Transport został utworzony',`${d.number} dodano do planera.`);e.target.reset()};
document.querySelectorAll('[data-fleet-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-fleet-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.fleet-subview').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`#fleet${b.dataset.fleetTab[0].toUpperCase()+b.dataset.fleetTab.slice(1)}`).classList.add('active')});
const driverModal=document.querySelector('#driverModal'),vehicleModal=document.querySelector('#vehicleModal');document.querySelector('#addDriverBtn').onclick=()=>driverModal.classList.add('open');document.querySelector('#addVehicleBtn').onclick=()=>vehicleModal.classList.add('open');document.querySelectorAll('[data-close-driver]').forEach(b=>b.onclick=()=>driverModal.classList.remove('open'));document.querySelectorAll('[data-close-vehicle]').forEach(b=>b.onclick=()=>vehicleModal.classList.remove('open'));
document.querySelector('#driverForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));drivers.push({name:`${d.firstName.trim()} ${d.lastName.trim()}`,phone:d.phone,email:d.email,license:d.license,until:d.licenseUntil,status:d.status});renderFleetManagement();driverModal.classList.remove('open');e.currentTarget.reset();showToast('Kierowca został dodany','Jest już dostępny przy przypisywaniu transportów.')};
document.querySelector('#vehicleForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));fleet.push({truck:d.truck.toUpperCase(),driver:'Nie przypisano',state:'Dostępny',km:'0 km',speed:'0 km/h',gps:d.gps==='Połączony'?'przed chwilą':'Brak',gpsConnected:d.gps==='Połączony',model:d.model,year:d.year,vin:d.vin,type:d.type});renderFleet();renderFleetManagement();vehicleModal.classList.remove('open');e.currentTarget.reset();showToast('Pojazd został dodany','Dodano go do struktury floty.')};
document.querySelector('#drawerClose').onclick=closeDrawer;document.querySelector('#drawerBackdrop').onclick=closeDrawer;
document.querySelectorAll('.preview-report').forEach(x=>x.onclick=()=>{switchView('reports')});
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTable(b.textContent.includes('uwagi')?transports.filter(t=>t.tone==='red'||t.tone==='amber'):transports.slice(0,4))});
document.querySelector('[data-target]').onclick=()=>document.querySelector('#attentionSection').scrollIntoView({behavior:'smooth'});
document.querySelectorAll('.truck-pin').forEach(p=>p.onclick=()=>showToast(p.dataset.truck,'Pozycja zaktualizowana 2 min temu.'));
document.querySelector('#optimizeBtn').onclick=()=>showToast('Analiza zakończona','Znaleziono 2 możliwe usprawnienia planu.');document.querySelector('#acceptPlan').onclick=()=>showToast('Scenariusz zastosowany','Przepięcie dodano do planu obu kierowców.');
function showToast(title,msg){const t=document.querySelector('#toast');t.querySelector('b').textContent=title;t.querySelector('p').textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function loadUserSession(){const raw=sessionStorage.getItem('lm_session')||localStorage.getItem('lm_session');if(!raw)return;try{const user=JSON.parse(raw);const fullName=`${user.firstName||''} ${user.lastName||''}`.trim();if(fullName){document.querySelector('#userName').textContent=fullName;document.querySelector('#userAvatar').textContent=`${user.firstName?.[0]||''}${user.lastName?.[0]||''}`.toUpperCase();document.querySelector('#pageTitle').textContent=`Dzień dobry, ${user.firstName}`;}document.querySelector('#userRole').textContent=user.role||'Użytkownik'}catch{localStorage.removeItem('lm_session');sessionStorage.removeItem('lm_session')}}
document.querySelector('#accountMenuBtn').onclick=e=>{e.stopPropagation();document.querySelector('#accountPopover').classList.toggle('open')};document.addEventListener('click',()=>document.querySelector('#accountPopover').classList.remove('open'));document.querySelector('#accountPopover').onclick=e=>e.stopPropagation();document.querySelector('#logoutBtn').onclick=()=>{localStorage.removeItem('lm_session');sessionStorage.removeItem('lm_session');location.href='auth.html'};
function openSettingsTab(name='company'){switchView('settings');document.querySelectorAll('.settings-nav button').forEach(b=>b.classList.toggle('active',b.dataset.settingsTab===name));document.querySelectorAll('.settings-panel').forEach(p=>p.classList.remove('active'));document.querySelector(`#${name}Settings`)?.classList.add('active')}
document.querySelectorAll('[data-settings-tab]').forEach(b=>b.onclick=()=>openSettingsTab(b.dataset.settingsTab));document.querySelectorAll('.settings-jump').forEach(b=>b.onclick=()=>openSettingsTab(b.dataset.settingsSection));document.querySelector('#openAccountSettings').onclick=()=>openSettingsTab('security');document.querySelectorAll('.settings-form').forEach(form=>form.onsubmit=e=>{e.preventDefault();const saved=document.querySelector('#settingsSaved');saved.textContent='Zapisano przed chwilą';showToast('Ustawienia zapisane','Konfiguracja została zaktualizowana.')});document.querySelectorAll('[data-test-connection]').forEach(b=>b.onclick=()=>{b.textContent='Testuję…';setTimeout(()=>{b.textContent='Połączenie działa ✓';showToast('Połączenie aktywne',`Połączono z ${b.dataset.testConnection}.`)},700)});document.querySelectorAll('.provider-choice button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.provider-choice button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
const fuelChange=document.querySelector('#fuelChange');if(fuelChange)fuelChange.oninput=()=>{const pct=Number(fuelChange.value),base=44600,projected=Math.round(base*(1+pct/100)),margin=(18.4-pct*.34).toFixed(1);document.querySelector('#fuelChangeLabel').textContent=`${pct>=0?'+':''}${pct}%`;document.querySelector('#projectedFuelCost').textContent=`${projected.toLocaleString('pl-PL')} €`;document.querySelector('#costDifference').textContent=`${projected-base>=0?'+':''}${(projected-base).toLocaleString('pl-PL')} €`;document.querySelector('#projectedMargin').textContent=`${margin}%`;document.querySelector('#marginDifference').textContent=`${pct>=0?'−':'+'}${Math.abs(pct*.34).toFixed(1)} pp`};document.querySelector('#refreshFuel')?.addEventListener('click',()=>showToast('Ceny odświeżone','Tryb demonstracyjny · źródło produkcyjne wymaga konfiguracji.'));document.querySelector('#recalculateRoutes')?.addEventListener('click',()=>showToast('Transporty przeliczone','2 zlecenia wymagają ponownej kontroli marży.'));
let onboardingStep=Number(localStorage.getItem('lm_onboarding_step')||0);const onboarding=document.querySelector('#onboarding');function showOnboarding(){onboarding.classList.add('open');onboarding.setAttribute('aria-hidden','false');renderOnboarding()}function closeOnboarding(){onboarding.classList.remove('open');onboarding.setAttribute('aria-hidden','true')}function renderOnboarding(){document.querySelectorAll('.onboarding-screen').forEach(s=>s.classList.toggle('active',Number(s.dataset.onboardingScreen)===onboardingStep));document.querySelectorAll('.onboarding-step').forEach(s=>{const n=Number(s.dataset.stepIndicator);s.classList.toggle('active',n===Math.min(onboardingStep,5));s.classList.toggle('done',n<onboardingStep)});document.querySelector('#onboardingCounter').textContent=onboardingStep<6?`Krok ${onboardingStep+1} z 6`:'Gotowe';document.querySelector('#onboardingBack').style.visibility=onboardingStep?'visible':'hidden';document.querySelector('#onboardingNext').textContent=onboardingStep===0?'Rozpocznij konfigurację →':onboardingStep===6?'Przejdź do aplikacji →':'Zapisz i przejdź dalej →'}function captureOnboardingStep(){if(onboardingStep===1)localStorage.setItem('lm_company',JSON.stringify({name:document.querySelector('#onboardCompany').value,nip:document.querySelector('#onboardNip').value,phone:document.querySelector('#onboardPhone').value}));if(onboardingStep===2){const truck=document.querySelector('#onboardTruck').value.trim().toUpperCase();if(truck&&!fleet.some(f=>f.truck===truck)){fleet.push({truck,driver:'Nie przypisano',state:'Dostępny',km:'0 km',speed:'0 km/h',gps:'Do podłączenia',gpsConnected:false,model:document.querySelector('#onboardModel').value||'Nie określono',year:'—'});renderFleet();renderFleetManagement();renderFuelFleet()}}if(onboardingStep===3){const first=document.querySelector('#onboardDriverFirst').value.trim(),last=document.querySelector('#onboardDriverLast').value.trim();if(first&&last&&!drivers.some(d=>d.name===`${first} ${last}`)){drivers.push({name:`${first} ${last}`,phone:document.querySelector('#onboardDriverPhone').value,email:'',license:document.querySelector('#onboardLicense').value||'Do uzupełnienia',until:'Do uzupełnienia',status:'Dostępny'});renderFleetManagement()}}if(onboardingStep===4&&document.querySelector('#onboardEmail').value)localStorage.setItem('lm_email_connected','true');if(onboardingStep===5&&document.querySelector('#onboardGpsLogin').value)localStorage.setItem('lm_gps_connected','true')}
document.querySelector('#onboardingNext').onclick=()=>{captureOnboardingStep();if(onboardingStep===6){localStorage.setItem('lm_onboarding_complete','true');localStorage.removeItem('lm_onboarding_pending');localStorage.removeItem('lm_onboarding_step');closeOnboarding();showToast('Konfiguracja zakończona','Logistic Master jest gotowy do pracy.');return}onboardingStep++;localStorage.setItem('lm_onboarding_step',onboardingStep);renderOnboarding()};document.querySelector('#onboardingBack').onclick=()=>{if(onboardingStep>0)onboardingStep--;localStorage.setItem('lm_onboarding_step',onboardingStep);renderOnboarding()};document.querySelector('#pauseOnboarding').onclick=()=>{localStorage.setItem('lm_onboarding_step',onboardingStep);closeOnboarding();showToast('Postęp został zapisany','Wznowisz konfigurację z menu konta.')};document.querySelector('#openOnboarding').onclick=()=>{onboardingStep=Number(localStorage.getItem('lm_onboarding_step')||0);showOnboarding()};document.querySelectorAll('.onboarding-test').forEach(b=>b.onclick=()=>{b.textContent='Testuję…';setTimeout(()=>{b.textContent='Połączenie działa ✓'},650)});
loadUserSession();if(localStorage.getItem('lm_onboarding_pending')==='true'&&localStorage.getItem('lm_onboarding_complete')!=='true')setTimeout(showOnboarding,250);
function renderFuelFleet(){const levels=[68,22,81,35,57,74],usage=[27.8,31.4,26.9,29.7,28.2,27.4],body=document.querySelector('#fuelFleetBody');if(!body)return;body.innerHTML=fleet.slice(0,6).map((f,i)=>{const level=levels[i]||50,low=level<30,range=Math.round(level*13.4),cost=(usage[i]*1.61/100).toFixed(2);return `<tr><td><div class="driver-cell"><span class="vehicle-mini">▰</span><div><strong>${f.truck}</strong><small>${f.driver}</small></div></div></td><td><div class="tank-level"><div><i class="${low?'low':''}" style="width:${level}%"></i></div><b>${level}%</b></div></td><td><strong>~${range} km</strong></td><td><strong>${usage[i]} l/100 km</strong><small>${usage[i]>30?'Powyżej normy':'W normie'}</small></td><td><strong>${cost} €/km</strong></td><td><span class="badge ${low?'red':'green'}">${low?'Zaplanuj tankowanie':'Poziom OK'}</span></td></tr>`}).join('')}
renderTable();renderCards();renderFleet();renderFleetManagement();renderFuelFleet();renderTimeline();renderReports();
