function currentWorkspaceEmail(){try{return JSON.parse(sessionStorage.getItem('lm_session')||localStorage.getItem('lm_session')||'null')?.email||'demo'}catch{return'demo'}}
const workspaceKey=`lm_workspace_${currentWorkspaceEmail()}`;
function readWorkspace(){try{return JSON.parse(localStorage.getItem(workspaceKey)||'null')}catch{return null}}
function saveWorkspace(){const snapshot={transports,fleet,drivers,updatedAt:new Date().toISOString()};localStorage.setItem(workspaceKey,JSON.stringify(snapshot));if(typeof previewWorkspace!=='undefined'&&!previewWorkspace)window.queueRemoteWorkspaceSync?.(snapshot)}
const savedWorkspace=readWorkspace();
const demoWorkspace=currentWorkspaceEmail()==='marek@firma.pl';
let previewWorkspace=!demoWorkspace&&!savedWorkspace;
const sampleTransports=[
 {id:'TR-2026-0718',client:'Nordic Freight AB',from:'Oslo, NO',to:'Göteborg, SE',driver:'Adam Nowak',truck:'ZS 8412K',progress:74,left:'128 km',eta:'Dzisiaj, 12:40',status:'W trasie',tone:'blue'},
 {id:'TR-2026-0719',client:'ScanLogistics AS',from:'Stockholm, SE',to:'Bergen, NO',driver:'Tomasz Lis',truck:'ZS 2209P',progress:46,left:'492 km',eta:'Dzisiaj, 18:20',status:'Ryzyko opóźnienia',tone:'red'},
 {id:'TR-2026-0720',client:'Baltic Cargo',from:'Malmö, SE',to:'Aarhus, DK',driver:'Piotr Wójcik',truck:'ZS 7731M',progress:82,left:'96 km',eta:'Dzisiaj, 10:55',status:'W trasie',tone:'blue'},
 {id:'TR-2026-0721',client:'Norway Express',from:'Kristiansand, NO',to:'Oslo, NO',driver:'Karol Maj',truck:'ZS 4421R',progress:21,left:'248 km',eta:'Dzisiaj, 15:30',status:'Postój',tone:'amber'},
 {id:'TR-2026-0722',client:'Svea Transport',from:'Helsingborg, SE',to:'Uppsala, SE',driver:'Michał Kot',truck:'ZS 1190T',progress:55,left:'284 km',eta:'Dzisiaj, 17:10',status:'W trasie',tone:'blue'},
 {id:'TR-2026-0723',client:'NordCargo',from:'Gothenburg, SE',to:'Trondheim, NO',driver:'Jan Kurek',truck:'ZS 9088W',progress:31,left:'602 km',eta:'Jutro, 08:00',status:'W trasie',tone:'blue'}
];
const sampleFleet=[
 {truck:'ZS 8412K',driver:'Adam Nowak',state:'W trasie',km:'412 km',speed:'76 km/h',gps:'1 min temu'},
 {truck:'ZS 2209P',driver:'Tomasz Lis',state:'Uwaga',km:'368 km',speed:'0 km/h',gps:'12 min temu'},
 {truck:'ZS 7731M',driver:'Piotr Wójcik',state:'W trasie',km:'501 km',speed:'82 km/h',gps:'2 min temu'},
 {truck:'ZS 4421R',driver:'Karol Maj',state:'Postój',km:'219 km',speed:'0 km/h',gps:'4 min temu'},
 {truck:'ZS 1190T',driver:'Michał Kot',state:'W trasie',km:'447 km',speed:'71 km/h',gps:'1 min temu'},
 {truck:'ZS 9088W',driver:'Jan Kurek',state:'W trasie',km:'390 km',speed:'79 km/h',gps:'3 min temu'}
];
const sampleDrivers=[
 {name:'Adam Nowak',phone:'+48 501 220 101',email:'adam@firma.pl',license:'SZA/10293',until:'2029-04-18',status:'W trasie'},
 {name:'Tomasz Lis',phone:'+48 501 220 102',email:'tomasz@firma.pl',license:'SZB/28411',until:'2028-11-02',status:'W trasie'},
 {name:'Piotr Wójcik',phone:'+48 501 220 103',email:'piotr@firma.pl',license:'SZC/14820',until:'2030-01-16',status:'W trasie'},
 {name:'Karol Maj',phone:'+48 501 220 104',email:'karol@firma.pl',license:'SZD/30125',until:'2027-08-30',status:'Postój'},
 {name:'Michał Kot',phone:'+48 501 220 105',email:'michal@firma.pl',license:'SZE/22109',until:'2029-06-12',status:'W trasie'},
 {name:'Jan Kurek',phone:'+48 501 220 106',email:'jan@firma.pl',license:'SZF/19877',until:'2028-03-22',status:'W trasie'}
];
let transports=savedWorkspace?.transports||[...((demoWorkspace||previewWorkspace)?sampleTransports:[])];
let fleet=savedWorkspace?.fleet||[...((demoWorkspace||previewWorkspace)?sampleFleet:[])];
let drivers=savedWorkspace?.drivers||[...((demoWorkspace||previewWorkspace)?sampleDrivers:[])];
function activateRealWorkspace(){if(!previewWorkspace)return;transports=[];fleet=[];drivers=[];previewWorkspace=false;const banner=document.querySelector('#demoDataBanner');if(banner)banner.hidden=true;renderTable();renderCards();renderFleet();renderFleetManagement();renderFuelFleet();renderTimeline();renderReports();renderWorkspaceSummary()}
const initials=n=>n.split(' ').map(x=>x[0]).join('');
function renderTable(list=transports.slice(0,4)){
 document.querySelector('#transportTableBody').innerHTML=list.map(t=>`<tr class="transport-row" data-id="${t.id}"><td><strong>${t.id}</strong><small>${t.client}</small></td><td><div class="route-cell"><span class="route-line"><i></i><span></span><i></i></span><div><strong>${t.from}</strong><small>${t.to}</small></div></div></td><td><div class="driver-cell"><span class="mini-avatar">${initials(t.driver)}</span><div><strong>${t.driver}</strong><small>${t.truck}</small></div></div></td><td><div class="progress-wrap"><div class="progress-meta"><span>${t.progress}%</span><span>${t.left}</span></div><div class="progress"><i style="width:${t.progress}%"></i></div></div></td><td><strong>${t.eta.split(',')[0]}</strong><small>${t.eta.split(',')[1]||''}</small></td><td><span class="badge ${t.tone}">${t.status}</span></td><td><button class="more-btn">•••</button></td></tr>`).join('');
 bindRows();
}
function renderCards(){document.querySelector('#transportCards').innerHTML=transports.map(t=>`<article class="panel transport-card transport-row" data-id="${t.id}"><div class="transport-card-head"><div><h3>${t.id}</h3><p>${t.client}</p></div><span class="badge ${t.tone}">${t.status}</span></div><div class="route-display"><div><b>${t.from.split(',')[0]}</b><span>${t.from.split(',')[1]}</span></div><span>···· ✈ ····</span><div><b>${t.to.split(',')[0]}</b><span>${t.to.split(',')[1]}</span></div></div><div class="progress-meta"><span>Postęp ${t.progress}%</span><span>${t.left} do celu</span></div><div class="progress"><i style="width:${t.progress}%"></i></div><div class="card-footer" style="margin-top:14px"><span class="mini-avatar">${initials(t.driver)}</span><div style="margin-left:8px"><b>${t.driver}</b><span style="display:block">${t.truck}</span></div><div style="text-align:right"><span>ETA</span><b style="display:block">${t.eta}</b></div></div></article>`).join('');bindRows()}
function renderFleet(){document.querySelector('#fleetGrid').innerHTML=fleet.map(f=>`<article class="fleet-card"><div class="fleet-card-head"><div><h3>${f.truck}</h3><p>Volvo FH 500</p></div><span class="badge ${f.state==='W trasie'?'green':f.state==='Uwaga'?'red':'amber'} fleet-status">${f.state}</span></div><div class="vehicle-illustration">▰</div><div class="driver-cell"><span class="mini-avatar">${initials(f.driver)}</span><div><strong>${f.driver}</strong><small>Kierowca</small></div></div><div class="fleet-stats"><div><span>Dzisiaj</span><b>${f.km}</b></div><div><span>Prędkość</span><b>${f.speed}</b></div><div><span>GPS</span><b>${f.gps}</b></div></div></article>`).join('')}
function renderFleetManagement(){document.querySelector('#driversCount').textContent=drivers.length;document.querySelector('#vehiclesCount').textContent=fleet.length;document.querySelector('#driversTable').innerHTML=`<div class="management-head"><span>KIEROWCA</span><span>KONTAKT</span><span>PRAWO JAZDY</span><span>STATUS</span><span></span></div>${drivers.map(d=>`<div class="management-row"><div class="entity-cell"><span class="mini-avatar">${initials(d.name)}</span><section><b>${d.name}</b><small>ID: DR-${String(drivers.indexOf(d)+1).padStart(3,'0')}</small></section></div><div><b>${d.phone}</b><small>${d.email||'Brak e-maila'}</small></div><div><b>${d.license}</b><small>ważne do ${d.until}</small></div><span><i class="entity-status ${d.status==='Nieaktywny'?'off':''}"></i>${d.status}</span><button class="more-btn">•••</button></div>`).join('')}`;document.querySelector('#vehiclesTable').innerHTML=`<div class="management-head vehicle-columns"><span>POJAZD</span><span>KIEROWCA</span><span>DANE GPS</span><span>STATUS</span><span></span></div>${fleet.map((f,i)=>`<div class="management-row vehicle-columns"><div class="entity-cell"><span class="vehicle-mini">▰</span><section><b>${f.truck}</b><small>${f.model||'Volvo FH 500'} · ${f.year||'2022'}</small></section></div><div><b>${f.driver}</b><small>${f.driver==='Nie przypisano'?'Wymaga przypisania':'Przypisany kierowca'}</small></div><div><b>${f.gpsConnected===false?'Do podłączenia':'Połączony'}</b><small>${f.gpsConnected===false?'Brak identyfikatora':f.gps}</small></div><span><i class="entity-status ${f.state==='Nieaktywny'?'off':''}"></i>${f.state}</span><button class="more-btn">•••</button></div>`).join('')}`;const select=document.querySelector('#transportForm select[name="driver"]');const selected=select.value;select.innerHTML=`<option>Nie przypisano</option>${drivers.filter(d=>d.status!=='Nieaktywny').map(d=>`<option>${d.name}</option>`).join('')}`;if([...select.options].some(o=>o.value===selected))select.value=selected}
function renderTimelineDemo(){document.querySelector('#timelineRows').innerHTML=fleet.slice(0,4).map((f,i)=>`<div class="timeline-row"><div class="timeline-person"><span class="mini-avatar">${initials(f.driver)}</span><div><strong>${f.driver}</strong><small>${f.truck}</small></div></div><div class="timeline-track"><div class="timeline-job ${['job-blue','job-orange','job-green','job-blue'][i]}" style="left:${[3,18,7,31][i]}%;width:${[54,47,68,49][i]}%"><b>${transports[i].from.split(',')[0]} → ${transports[i].to.split(',')[0]}</b>${transports[i].id}</div></div></div>`).join('')}
function renderReportsDemo(){const t=transports[0];document.querySelector('#reportsWorkspace').innerHTML=`<div class="report-sidebar">${transports.slice(0,4).map((x,i)=>`<div class="report-select ${i===0?'active':''}" data-report="${x.id}"><h4>${x.client}</h4><p>${x.id} · ${x.to}</p><span class="badge ${x.tone==='red'?'amber':'green'}">${x.tone==='red'?'Wymaga sprawdzenia':'Gotowy'}</span></div>`).join('')}</div><div class="email-preview"><span class="eyebrow">WERSJA ROBOCZA WIADOMOŚCI</span><label><span>Do:</span><input value="operations@nordicfreight.se"></label><label><span>Temat:</span><input value="Transport update · ${t.id}"></label><div class="email-body" contenteditable="true">Good morning,<br><br>The vehicle carrying shipment <strong>${t.id}</strong> is currently on the route from ${t.from} to ${t.to}. The vehicle has completed ${t.progress}% of the route and is approximately <strong>${t.left}</strong> from the delivery location.<br><br>Estimated arrival: <strong>${t.eta}</strong>. The delivery remains on schedule. We will inform you if the situation changes.<br><br>Best regards,<br>Logistics Team</div><div class="email-actions"><button class="secondary-btn">Kopiuj treść</button><button class="primary-btn send-draft">Utwórz draft e-mail</button></div></div>`;document.querySelector('.send-draft').onclick=()=>showToast('Draft został przygotowany','Wiadomość oczekuje na wysłanie.')}
function bindRows(){document.querySelectorAll('.transport-row').forEach(row=>row.onclick=()=>openTransport(row.dataset.id))}
function openTransport(id){const t=transports.find(x=>x.id===id);if(!t)return;document.querySelector('#drawerContent').innerHTML=`<div class="drawer-header"><span class="eyebrow">${t.id}</span><h2>${t.client}</h2><p>Aktywny transport · dane z aplikacji GPS</p></div><span class="badge ${t.tone}">${t.status}</span><div class="drawer-route"><div><i></i><section><small>ZAŁADUNEK</small><b>${t.from}</b></section></div><span></span><div><i></i><section><small>ROZŁADUNEK</small><b>${t.to}</b></section></div></div><div class="drawer-section"><h3>Realizacja</h3><div class="progress-meta"><span>${t.progress}% trasy</span><span>${t.left} do celu</span></div><div class="progress"><i style="width:${t.progress}%"></i></div></div><div class="drawer-section"><h3>Zasoby</h3><div class="drawer-grid"><div><span>Kierowca</span><b>${t.driver}</b></div><div><span>Ciągnik</span><b>${t.truck}</b></div><div><span>Naczepa</span><b>N-${Math.ceil(Math.random()*20).toString().padStart(2,'0')}</b></div><div><span>Planowane ETA</span><b>${t.eta}</b></div></div></div><div class="drawer-section"><h3>Ostatnia pozycja GPS</h3><p>Okolice Jönköping, E4 · zaktualizowano 2 min temu</p></div><button class="primary-btn full">Przygotuj raport dla klienta</button>`;document.querySelector('#detailDrawer').classList.add('open');document.querySelector('#drawerBackdrop').classList.add('open')}
function closeDrawer(){document.querySelector('#detailDrawer').classList.remove('open');document.querySelector('#drawerBackdrop').classList.remove('open')}
const titles={dashboard:'Dzień dobry, Marek',transports:'Transporty',planner:'Planer tras',fleet:'Flota i kierowcy',reports:'Raporty',inbox:'Skrzynka zleceń',kilometers:'Kilometry',fuel:'Paliwo i marża',settlements:'Rozliczenia',settings:'Ustawienia'};
function getSessionUser(){try{return JSON.parse(sessionStorage.getItem('lm_session')||localStorage.getItem('lm_session')||'null')}catch{return null}}
function switchView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#${name}View`)?.classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===name));const sessionUser=getSessionUser();document.querySelector('#pageTitle').textContent=name==='dashboard'?`Dzień dobry, ${sessionUser?.firstName||'Marek'}`:(titles[name]||'Logistic Master');document.querySelector('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>switchView(n.dataset.view));document.querySelectorAll('[data-view-jump]').forEach(n=>n.onclick=()=>switchView(n.dataset.viewJump));
document.querySelector('#mobileMenu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');
const modal=document.querySelector('#transportModal');document.querySelector('#newTransportBtn').onclick=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false')};document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});
const sampleMail=`Temat: New transport order 84721 / Malmö - Oslo

Good morning,
please arrange transport for Nordic Freight AB.
Loading: Malmö, Sweden, 21.07.2026 between 08:00-09:00.
Delivery: Oslo, Norway, no later than 21.07.2026 at 18:30.
Reference number: NF-84721.
Cargo: 24 pallets, 18,400 kg. Please report vehicle position in the morning.
Best regards, Anna`;
const aiPanel=document.querySelector('#aiImportPanel');
document.querySelector('#aiImportBtn').onclick=()=>{aiPanel.classList.toggle('open');if(aiPanel.classList.contains('open'))document.querySelector('#emailSource').focus()};
document.querySelector('#useSampleMail').onclick=()=>{document.querySelector('#emailSource').value=sampleMail};
document.querySelector('#showSourceBtn').onclick=()=>{aiPanel.classList.add('open');document.querySelector('#emailSource').scrollIntoView({behavior:'smooth',block:'center'})};
document.querySelector('#analyzeEmailBtn').onclick=()=>{const source=document.querySelector('#emailSource').value.trim();if(!source){showToast('Brakuje treści wiadomości','Wklej maila, który mamy przeanalizować.');return}const btn=document.querySelector('#analyzeEmailBtn');btn.disabled=true;btn.textContent='✦ Analizuję…';setTimeout(()=>{const form=document.querySelector('#transportForm');form.elements.number.value='NF-84721';form.elements.client.value='Nordic Freight AB';form.elements.from.value='Malmö, SE';form.elements.to.value='Oslo, NO';form.elements.date.value='2026-07-21T18:30';form.elements.notes.value='Załadunek 08:00–09:00 · 24 palety · 18 400 kg · wymagany raport poranny';document.querySelectorAll('.confidence').forEach(c=>{c.classList.add('show');const medium=c.dataset.confidence==='notes';c.classList.add(medium?'medium':'high');c.textContent=medium?'82% — sprawdź':'98% pewności';c.closest('label').classList.toggle('field-highlight',medium)});document.querySelector('#extractionResult').classList.add('show');aiPanel.classList.remove('open');btn.disabled=false;btn.textContent='✦ Analizuj wiadomość';showToast('AI odczytało zlecenie','Sprawdź uzupełnione pola przed zatwierdzeniem.');},850)};
document.querySelector('#transportForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));activateRealWorkspace();transports.unshift({id:d.number,client:d.client,from:d.from,to:d.to,driver:d.driver,truck:'Do przypisania',progress:0,left:'—',eta:d.date.replace('T',' '),status:'Nowy',tone:'green'});saveWorkspace();renderTable();renderCards();renderWorkspaceSummary();modal.classList.remove('open');showToast('Transport został utworzony',`${d.number} dodano do planera.`);e.target.reset()};
document.querySelectorAll('[data-fleet-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-fleet-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.fleet-subview').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`#fleet${b.dataset.fleetTab[0].toUpperCase()+b.dataset.fleetTab.slice(1)}`).classList.add('active')});
const driverModal=document.querySelector('#driverModal'),vehicleModal=document.querySelector('#vehicleModal');document.querySelector('#addDriverBtn').onclick=()=>driverModal.classList.add('open');document.querySelector('#addVehicleBtn').onclick=()=>vehicleModal.classList.add('open');document.querySelectorAll('[data-close-driver]').forEach(b=>b.onclick=()=>driverModal.classList.remove('open'));document.querySelectorAll('[data-close-vehicle]').forEach(b=>b.onclick=()=>vehicleModal.classList.remove('open'));
document.querySelector('#driverForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));activateRealWorkspace();drivers.push({name:`${d.firstName.trim()} ${d.lastName.trim()}`,phone:d.phone,email:d.email,license:d.license,until:d.licenseUntil,status:d.status});saveWorkspace();renderFleetManagement();renderWorkspaceSummary();driverModal.classList.remove('open');e.currentTarget.reset();showToast('Kierowca został dodany','Jest już dostępny przy przypisywaniu transportów.')};
document.querySelector('#vehicleForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));activateRealWorkspace();fleet.push({truck:d.truck.toUpperCase(),driver:'Nie przypisano',state:'Dostępny',km:'0 km',speed:'0 km/h',gps:d.gps==='Połączony'?'przed chwilą':'Brak',gpsConnected:d.gps==='Połączony',model:d.model,year:d.year,vin:d.vin,type:d.type});saveWorkspace();renderFleet();renderFleetManagement();renderFuelFleet();renderWorkspaceSummary();vehicleModal.classList.remove('open');e.currentTarget.reset();showToast('Pojazd został dodany','Dodano go do struktury floty.')};
document.querySelector('#drawerClose').onclick=closeDrawer;document.querySelector('#drawerBackdrop').onclick=closeDrawer;
document.querySelectorAll('.preview-report').forEach(x=>x.onclick=()=>{switchView('reports')});
document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTable(b.textContent.includes('uwagi')?transports.filter(t=>t.tone==='red'||t.tone==='amber'):transports.slice(0,4))});
document.querySelector('[data-target]').onclick=()=>document.querySelector('#attentionSection').scrollIntoView({behavior:'smooth'});
document.querySelectorAll('.truck-pin').forEach(p=>p.onclick=()=>showToast(p.dataset.truck,'Pozycja zaktualizowana 2 min temu.'));
document.querySelector('#optimizeBtn').onclick=()=>showToast('Analiza zakończona','Znaleziono 2 możliwe usprawnienia planu.');document.querySelector('#acceptPlan').onclick=()=>showToast('Scenariusz zastosowany','Przepięcie dodano do planu obu kierowców.');
function showToast(title,msg){const t=document.querySelector('#toast');t.querySelector('b').textContent=title;t.querySelector('p').textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function loadUserSession(){const raw=sessionStorage.getItem('lm_session')||localStorage.getItem('lm_session');if(!raw)return;try{const user=JSON.parse(raw);const fullName=`${user.firstName||''} ${user.lastName||''}`.trim();if(fullName){document.querySelector('#userName').textContent=fullName;document.querySelector('#userAvatar').textContent=`${user.firstName?.[0]||''}${user.lastName?.[0]||''}`.toUpperCase();document.querySelector('#pageTitle').textContent=`Dzień dobry, ${user.firstName}`;}document.querySelector('#userRole').textContent=user.role||'Użytkownik'}catch{localStorage.removeItem('lm_session');sessionStorage.removeItem('lm_session')}}
document.querySelector('#accountMenuBtn').onclick=e=>{e.stopPropagation();document.querySelector('#accountPopover').classList.toggle('open')};document.addEventListener('click',()=>document.querySelector('#accountPopover').classList.remove('open'));document.querySelector('#accountPopover').onclick=e=>e.stopPropagation();document.querySelector('#logoutBtn').onclick=async()=>{await window.lmSupabase?.auth.signOut();localStorage.removeItem('lm_session');sessionStorage.removeItem('lm_session');location.href='auth.html'};
function openSettingsTab(name='company'){switchView('settings');document.querySelectorAll('.settings-nav button').forEach(b=>b.classList.toggle('active',b.dataset.settingsTab===name));document.querySelectorAll('.settings-panel').forEach(p=>p.classList.remove('active'));document.querySelector(`#${name}Settings`)?.classList.add('active')}
document.querySelectorAll('[data-settings-tab]').forEach(b=>b.onclick=()=>openSettingsTab(b.dataset.settingsTab));document.querySelectorAll('.settings-jump').forEach(b=>b.onclick=()=>openSettingsTab(b.dataset.settingsSection));document.querySelector('#openAccountSettings').onclick=()=>openSettingsTab('security');document.querySelectorAll('.settings-form').forEach(form=>form.onsubmit=e=>{e.preventDefault();const saved=document.querySelector('#settingsSaved');saved.textContent='Zapisano przed chwilą';showToast('Ustawienia zapisane','Konfiguracja została zaktualizowana.')});document.querySelectorAll('[data-test-connection]').forEach(b=>b.onclick=()=>{b.textContent='Testuję…';setTimeout(()=>{b.textContent='Połączenie działa ✓';showToast('Połączenie aktywne',`Połączono z ${b.dataset.testConnection}.`)},700)});document.querySelectorAll('.provider-choice button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.provider-choice button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
const fuelChange=document.querySelector('#fuelChange');if(fuelChange)fuelChange.oninput=()=>{const pct=Number(fuelChange.value),base=44600,projected=Math.round(base*(1+pct/100)),margin=(18.4-pct*.34).toFixed(1);document.querySelector('#fuelChangeLabel').textContent=`${pct>=0?'+':''}${pct}%`;document.querySelector('#projectedFuelCost').textContent=`${projected.toLocaleString('pl-PL')} €`;document.querySelector('#costDifference').textContent=`${projected-base>=0?'+':''}${(projected-base).toLocaleString('pl-PL')} €`;document.querySelector('#projectedMargin').textContent=`${margin}%`;document.querySelector('#marginDifference').textContent=`${pct>=0?'−':'+'}${Math.abs(pct*.34).toFixed(1)} pp`};document.querySelector('#refreshFuel')?.addEventListener('click',()=>showToast('Ceny odświeżone','Tryb demonstracyjny · źródło produkcyjne wymaga konfiguracji.'));document.querySelector('#recalculateRoutes')?.addEventListener('click',()=>showToast('Transporty przeliczone','2 zlecenia wymagają ponownej kontroli marży.'));
let onboardingDraft=JSON.parse(localStorage.getItem(workspaceKey+'_onboarding_draft')||'{}');function saveOnboardingDraft(){localStorage.setItem(workspaceKey+'_onboarding_draft',JSON.stringify(onboardingDraft))}let onboardingStep=Number(localStorage.getItem('lm_onboarding_step')||0);const onboarding=document.querySelector('#onboarding');function showOnboarding(){onboarding.classList.add('open');onboarding.setAttribute('aria-hidden','false');renderOnboarding()}function closeOnboarding(){onboarding.classList.remove('open');onboarding.setAttribute('aria-hidden','true')}function renderOnboarding(){document.querySelectorAll('.onboarding-screen').forEach(s=>s.classList.toggle('active',Number(s.dataset.onboardingScreen)===onboardingStep));document.querySelectorAll('.onboarding-step').forEach(s=>{const n=Number(s.dataset.stepIndicator);s.classList.toggle('active',n===Math.min(onboardingStep,5));s.classList.toggle('done',n<onboardingStep)});document.querySelector('#onboardingCounter').textContent=onboardingStep<6?`Krok ${onboardingStep+1} z 6`:'Gotowe';document.querySelector('#onboardingBack').style.visibility=onboardingStep?'visible':'hidden';document.querySelector('#onboardingNext').textContent=onboardingStep===0?'Rozpocznij konfigurację →':onboardingStep===6?'Przejdź do aplikacji →':'Zapisz i przejdź dalej →'}function captureOnboardingStep(){if(onboardingStep===1)localStorage.setItem('lm_company',JSON.stringify({name:document.querySelector('#onboardCompany').value,nip:document.querySelector('#onboardNip').value,phone:document.querySelector('#onboardPhone').value}));if(onboardingStep===2){const truck=document.querySelector('#onboardTruck').value.trim().toUpperCase();if(truck){onboardingDraft.vehicle={truck,driver:'Nie przypisano',state:'Dostępny',km:'0 km',speed:'0 km/h',gps:'Do podłączenia',gpsConnected:false,model:document.querySelector('#onboardModel').value||'Nie określono',year:'—'};saveOnboardingDraft()}}if(onboardingStep===3){const first=document.querySelector('#onboardDriverFirst').value.trim(),last=document.querySelector('#onboardDriverLast').value.trim();if(first&&last){onboardingDraft.driver={name:first+' '+last,phone:document.querySelector('#onboardDriverPhone').value,email:'',license:document.querySelector('#onboardLicense').value||'Do uzupełnienia',until:'Do uzupełnienia',status:'Dostępny'};saveOnboardingDraft()}}if(onboardingStep===4&&document.querySelector('#onboardEmail').value)localStorage.setItem('lm_email_connected','true');if(onboardingStep===5&&document.querySelector('#onboardGpsLogin').value)localStorage.setItem('lm_gps_connected','true')}
document.querySelector('#onboardingNext').onclick=()=>{captureOnboardingStep();if(onboardingStep===6){activateRealWorkspace();if(onboardingDraft.vehicle)fleet.push(onboardingDraft.vehicle);if(onboardingDraft.driver)drivers.push(onboardingDraft.driver);localStorage.removeItem(workspaceKey+'_onboarding_draft');onboardingDraft={};saveWorkspace();renderTable();renderCards();renderFleet();renderFleetManagement();renderFuelFleet();renderTimeline();renderReports();renderWorkspaceSummary();localStorage.setItem('lm_onboarding_complete','true');localStorage.removeItem('lm_onboarding_pending');localStorage.removeItem('lm_onboarding_step');closeOnboarding();showToast('Konfiguracja zakończona','Logistic Master jest gotowy do pracy.');return}onboardingStep++;localStorage.setItem('lm_onboarding_step',onboardingStep);renderOnboarding()};document.querySelector('#onboardingBack').onclick=()=>{if(onboardingStep>0)onboardingStep--;localStorage.setItem('lm_onboarding_step',onboardingStep);renderOnboarding()};document.querySelector('#pauseOnboarding').onclick=()=>{localStorage.setItem('lm_onboarding_step',onboardingStep);closeOnboarding();showToast('Postęp został zapisany','Wznowisz konfigurację z menu konta.')};document.querySelector('#openOnboarding').onclick=()=>{onboardingStep=Number(localStorage.getItem('lm_onboarding_step')||0);showOnboarding()};document.querySelectorAll('.onboarding-test').forEach(b=>b.onclick=()=>{b.textContent='Testuję…';setTimeout(()=>{b.textContent='Połączenie działa ✓'},650)});
document.querySelector('#continueOnboarding').onclick=showOnboarding;loadUserSession();const needsWorkspaceSetup=!demoWorkspace&&!savedWorkspace;if((localStorage.getItem('lm_onboarding_pending')==='true'&&localStorage.getItem('lm_onboarding_complete')!=='true')||needsWorkspaceSetup)setTimeout(showOnboarding,250);
function renderTimeline(){if(transports.length>=Math.min(fleet.length,4))return renderTimelineDemo();document.querySelector('#timelineRows').innerHTML=fleet.slice(0,4).map(f=>`<div class="timeline-row"><div class="timeline-person"><span class="mini-avatar">${initials(f.driver)}</span><div><strong>${f.driver}</strong><small>${f.truck}</small></div></div><div class="timeline-track"><div class="timeline-empty">Brak przypisanego transportu</div></div></div>`).join('')||'<div class="workspace-empty compact"><b>Brak zasobów w planerze</b><span>Dodaj pojazdy i kierowców w module floty.</span></div>'}
function renderReports(){if(transports.length)return renderReportsDemo();document.querySelector('#reportsWorkspace').innerHTML='<div class="workspace-empty"><b>Brak raportów</b><span>Raporty pojawią się po dodaniu pierwszego transportu.</span></div>'}
function renderWorkspaceSummary(){const banner=document.querySelector('#demoDataBanner');if(banner)banner.hidden=!previewWorkspace;const metricCards=document.querySelectorAll('.metric-card');if(metricCards[0])metricCards[0].querySelector('.metric-copy strong').textContent=transports.length;if(metricCards[1])metricCards[1].querySelector('.metric-copy strong').innerHTML=`${fleet.filter(f=>f.state==='W trasie').length} <em>/ ${fleet.length}</em>`;const navTransport=document.querySelector('[data-view="transports"] .nav-count');if(navTransport)navTransport.textContent=transports.length;if(!transports.length){document.querySelector('#transportTableBody').innerHTML='<tr><td colspan="7"><div class="workspace-empty compact"><b>Nie masz jeszcze transportów</b><span>Dodaj pierwszy transport ręcznie albo wczytaj zlecenie z maila.</span></div></td></tr>';document.querySelector('#transportCards').innerHTML='<div class="workspace-empty"><b>Brak transportów</b><span>Nowe zlecenia pojawią się tutaj.</span></div>'}if(!fleet.length)document.querySelector('#fleetGrid').innerHTML='<div class="workspace-empty"><b>Flota jest pusta</b><span>Dodaj pierwszy pojazd w zakładce „Pojazdy”.</span></div>';if(!demoWorkspace){const alertStrip=document.querySelector('.alert-strip');const risky=transports.filter(t=>t.tone==='red'||t.tone==='amber').length;alertStrip.querySelector('strong').textContent=risky?`${risky} transporty wymagają uwagi`:'Brak alertów operacyjnych';alertStrip.querySelector('p').textContent=risky?'Sprawdź terminy oraz aktualność danych GPS.':'Wszystkie dodane operacje wyglądają prawidłowo.';if(metricCards[2])metricCards[2].querySelector('.metric-copy strong').innerHTML=`${fleet.reduce((sum,f)=>sum+(parseInt(f.km)||0),0).toLocaleString('pl-PL')} <em>km</em>`;if(metricCards[3])metricCards[3].querySelector('.metric-copy strong').innerHTML=transports.length?'—<em>%</em>':'—';const reportBadge=document.querySelector('.report-panel .badge.amber');if(reportBadge)reportBadge.textContent=`${transports.length} oczekuje`;const connected=fleet.filter(f=>f.gpsConnected);document.querySelectorAll('.truck-pin').forEach((pin,i)=>{pin.style.display=connected[i]?'flex':'none';if(connected[i])pin.querySelector('b').textContent=connected[i].truck});const reportList=document.querySelector('.report-list');reportList.innerHTML=transports.slice(0,3).map(t=>`<div class="report-row"><div class="company-logo north">${t.client[0]||'T'}</div><div><strong>${t.client}</strong><span>${t.id} · ${t.to}</span></div><span class="badge amber">Do przygotowania</span><button class="row-action">›</button></div>`).join('')||'<div class="workspace-empty compact"><b>Brak raportów porannych</b><span>Najpierw dodaj aktywny transport.</span></div>'}}
function renderFuelFleet(){const levels=[68,22,81,35,57,74],usage=[27.8,31.4,26.9,29.7,28.2,27.4],body=document.querySelector('#fuelFleetBody');if(!body)return;body.innerHTML=fleet.slice(0,6).map((f,i)=>{const hasGps=f.gpsConnected!==false,level=hasGps?(levels[i]||50):null,low=level!==null&&level<30,range=level===null?'—':`~${Math.round(level*13.4)} km`,cost=hasGps?(usage[i]*1.61/100).toFixed(2):'—';return `<tr><td><div class="driver-cell"><span class="vehicle-mini">▰</span><div><strong>${f.truck}</strong><small>${f.driver}</small></div></div></td><td>${level===null?'<span class="badge amber">Brak danych GPS</span>':`<div class="tank-level"><div><i class="${low?'low':''}" style="width:${level}%"></i></div><b>${level}%</b></div>`}</td><td><strong>${range}</strong></td><td><strong>${hasGps?usage[i]+' l/100 km':'—'}</strong></td><td><strong>${cost}${hasGps?' €/km':''}</strong></td><td><span class="badge ${low?'red':hasGps?'green':'amber'}">${low?'Zaplanuj tankowanie':hasGps?'Poziom OK':'Podłącz GPS'}</span></td></tr>`}).join('')||'<tr><td colspan="6"><div class="workspace-empty compact"><b>Brak pojazdów</b><span>Dodaj flotę, aby rozpocząć analizę paliwa.</span></div></td></tr>'}
{
/* Logic hardening layer: account-scoped state, safe rendering and honest integration states. */
const userStateKey=suffix=>`lm_user_${currentWorkspaceEmail().toLowerCase()}_${suffix}`;
const safeText=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeParse=(value,fallback)=>{try{return JSON.parse(value)??fallback}catch{return fallback}};
const userSettings=safeParse(localStorage.getItem(userStateKey('settings')),{company:{},gps:{connected:false},email:{connected:false},ai:{},notifications:{},privacy:{},fuel:{}});
if(!demoWorkspace){fleet.forEach(vehicle=>{if(!vehicle.gpsVerified){vehicle.gpsConnected=false;vehicle.gps='Brak synchronizacji';delete vehicle.fuelLevel;delete vehicle.fuelUsage}});if(savedWorkspace)saveWorkspace()}
function persistSettings(){localStorage.setItem(userStateKey('settings'),JSON.stringify(userSettings));window.syncRemoteSettings?.(userSettings)}
function renderSafeSummary(){const banner=document.querySelector('#demoDataBanner');if(banner)banner.hidden=!previewWorkspace;const cards=document.querySelectorAll('.metric-card');cards[0]?.querySelector('.metric-copy strong')?.replaceChildren(String(transports.length));if(cards[1])cards[1].querySelector('.metric-copy strong').innerHTML=`${fleet.filter(f=>f.state==='W trasie').length} <em>/ ${fleet.length}</em>`;if(cards[2])cards[2].querySelector('.metric-copy strong').innerHTML=`${fleet.reduce((sum,f)=>sum+(parseInt(f.km)||0),0).toLocaleString('pl-PL')} <em>km</em>`;if(cards[3])cards[3].querySelector('.metric-copy strong').innerHTML='—<em>%</em>';const nav=document.querySelector('[data-view="transports"] .nav-count');if(nav)nav.textContent=transports.length;const alert=document.querySelector('.alert-strip'),risky=transports.filter(t=>t.tone==='red'||t.tone==='amber').length;if(alert&&!demoWorkspace){alert.querySelector('strong').textContent=risky?`${risky} transporty wymagają uwagi`:'Brak alertów operacyjnych';alert.querySelector('p').textContent=risky?'Sprawdź terminy oraz aktualność danych GPS.':'Wszystkie dodane operacje wyglądają prawidłowo.';alert.querySelector('button').hidden=!risky}if(!transports.length){document.querySelector('#transportTableBody').innerHTML='<tr><td colspan="7"><div class="workspace-empty compact"><b>Nie masz jeszcze transportów</b><span>Dodaj pierwszy transport ręcznie albo wczytaj zlecenie z maila.</span></div></td></tr>';document.querySelector('#transportCards').innerHTML='<div class="workspace-empty"><b>Brak transportów</b><span>Nowe zlecenia pojawią się tutaj.</span></div>'}if(!fleet.length)document.querySelector('#fleetGrid').innerHTML='<div class="workspace-empty"><b>Flota jest pusta</b><span>Dodaj pierwszy pojazd w zakładce „Pojazdy”.</span></div>';if(!demoWorkspace){document.querySelectorAll('.truck-pin').forEach(pin=>pin.style.display='none');const reportList=document.querySelector('.report-list');reportList.innerHTML=transports.slice(0,3).map(t=>`<div class="report-row"><div class="company-logo north">${safeText(t.client?.[0]||'T')}</div><div><strong>${safeText(t.client)}</strong><span>${safeText(t.id)} · ${safeText(t.to)}</span></div><span class="badge amber">Do przygotowania</span><button class="row-action preview-report" data-report-id="${safeText(t.id)}">›</button></div>`).join('')||'<div class="workspace-empty compact"><b>Brak raportów porannych</b><span>Najpierw dodaj aktywny transport.</span></div>'}}
function updateNotificationCounts(){const reportCount=transports.length,inboxCount=0,fuelCount=fleet.filter(vehicle=>Number.isFinite(Number(vehicle.fuelLevel))&&Number(vehicle.fuelLevel)<30).length,riskCount=transports.filter(transport=>transport.tone==='red'||transport.tone==='amber').length,gpsCount=userSettings.gps?.connected?fleet.filter(vehicle=>vehicle.gpsStale===true).length:0,total=riskCount+inboxCount+fuelCount+gpsCount;const setNav=(view,count)=>{const badge=document.querySelector(`[data-view="${view}"] .nav-count`);if(!badge)return;badge.textContent=count;badge.hidden=count===0};setNav('transports',transports.length);setNav('reports',reportCount);setNav('inbox',inboxCount);setNav('fuel',fuelCount);const notification=document.querySelector('.notification span');if(notification){notification.textContent=total;notification.hidden=total===0}const reportBadge=document.querySelector('.report-panel .badge.amber');if(reportBadge){reportBadge.textContent=`${reportCount} oczekuje`;reportBadge.hidden=reportCount===0}document.querySelector('[data-settings-tab="gpsApp"] .status-mini')?.classList.toggle('connected',Boolean(userSettings.gps?.connected));document.querySelector('[data-settings-tab="email"] .status-mini')?.classList.toggle('connected',Boolean(userSettings.email?.connected));const button=document.querySelector('.notification');if(button)button.onclick=()=>showToast(total?'Aktywne powiadomienia':'Brak nowych powiadomień',total?`Opóźnienia: ${riskCount}, paliwo: ${fuelCount}, GPS: ${gpsCount}.`:'Powiadomienia pojawią się dopiero na podstawie rzeczywistych danych.')}
function refreshAll(){saveWorkspace();renderTable();renderCards();renderFleet();renderFleetManagement();renderFuelFleet();renderTimeline();renderReports();renderSafeSummary();updateNotificationCounts()}
window.applyRemoteWorkspace=workspace=>{if(!workspace)return;transports=workspace.transports||[];fleet=workspace.fleet||[];drivers=workspace.drivers||[];previewWorkspace=false;localStorage.setItem(workspaceKey,JSON.stringify(workspace));renderTable();renderCards();renderFleet();renderFleetManagement();renderFuelFleet();renderTimeline();renderReports();renderSafeSummary();updateNotificationCounts()};
function updateCloudSyncStatus(status=window.lmLastSyncStatus){const chip=document.querySelector('#cloudSyncStatus');if(!chip||!status)return;chip.dataset.state=status.state;chip.querySelector('b').textContent=status.label}
document.addEventListener('lm:sync-status',event=>updateCloudSyncStatus(event.detail));updateCloudSyncStatus();
function loadHardenedUserSession(){const raw=sessionStorage.getItem('lm_session')||localStorage.getItem('lm_session');const session=safeParse(raw,null);if(!session)return;const account=safeParse(localStorage.getItem('lm_accounts'),[]).find(item=>item.email===session.email);if(!account)return;const fullName=`${account.firstName||''} ${account.lastName||''}`.trim();document.querySelector('#userName').textContent=fullName||account.email;document.querySelector('#userAvatar').textContent=`${account.firstName?.[0]||''}${account.lastName?.[0]||''}`.toUpperCase()||'U';document.querySelector('#pageTitle').textContent=`Dzień dobry, ${account.firstName||'Użytkowniku'}`;document.querySelector('#userRole').textContent=account.role||'Użytkownik'}
function initialsSafe(name){return String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'?'}
function renderTable(list=transports.slice(0,4)){const body=document.querySelector('#transportTableBody');body.innerHTML=list.map(t=>`<tr class="transport-row" data-id="${safeText(t.id)}"><td><strong>${safeText(t.id)}</strong><small>${safeText(t.client)}</small></td><td><div class="route-cell"><span class="route-line"><i></i><span></span><i></i></span><div><strong>${safeText(t.from)}</strong><small>${safeText(t.to)}</small></div></div></td><td><div class="driver-cell"><span class="mini-avatar">${initialsSafe(t.driver)}</span><div><strong>${safeText(t.driver||'Nie przypisano')}</strong><small>${safeText(t.truck||'Nie przypisano')}</small></div></div></td><td><div class="progress-wrap"><div class="progress-meta"><span>${Number(t.progress)||0}%</span><span>${safeText(t.left||'—')}</span></div><div class="progress"><i style="width:${Math.min(100,Math.max(0,Number(t.progress)||0))}%"></i></div></div></td><td><strong>${safeText(String(t.eta||'—').split(',')[0])}</strong><small>${safeText(String(t.eta||'').split(',').slice(1).join(','))}</small></td><td><span class="badge ${['red','amber','blue','green'].includes(t.tone)?t.tone:'blue'}">${safeText(t.status||'Nowy')}</span></td><td><button class="more-btn entity-delete" data-kind="transport" data-key="${safeText(t.id)}" aria-label="Usuń transport">Usuń</button></td></tr>`).join('');bindRows()}
function renderCards(){document.querySelector('#transportCards').innerHTML=transports.map(t=>`<article class="panel transport-card transport-row" data-id="${safeText(t.id)}"><div class="transport-card-head"><div><h3>${safeText(t.id)}</h3><p>${safeText(t.client)}</p></div><span class="badge ${['red','amber','blue','green'].includes(t.tone)?t.tone:'blue'}">${safeText(t.status)}</span></div><div class="route-display"><div><b>${safeText(t.from)}</b></div><span>···· → ····</span><div><b>${safeText(t.to)}</b></div></div><div class="progress-meta"><span>Postęp ${Number(t.progress)||0}%</span><span>${safeText(t.left||'—')} do celu</span></div><div class="progress"><i style="width:${Math.min(100,Math.max(0,Number(t.progress)||0))}%"></i></div><div class="card-footer" style="margin-top:14px"><span class="mini-avatar">${initialsSafe(t.driver)}</span><div style="margin-left:8px"><b>${safeText(t.driver||'Nie przypisano')}</b><span style="display:block">${safeText(t.truck||'Nie przypisano')}</span></div><div style="text-align:right"><span>ETA</span><b style="display:block">${safeText(t.eta||'—')}</b></div></div></article>`).join('');bindRows()}
function renderFleet(){document.querySelector('#fleetGrid').innerHTML=fleet.map(f=>`<article class="fleet-card"><div class="fleet-card-head"><div><h3>${safeText(f.truck)}</h3><p>${safeText(f.model||'Nie określono')}</p></div><span class="badge ${f.state==='W trasie'?'green':f.state==='Uwaga'?'red':'amber'} fleet-status">${safeText(f.state)}</span></div><div class="vehicle-illustration">▰</div><div class="driver-cell"><span class="mini-avatar">${initialsSafe(f.driver)}</span><div><strong>${safeText(f.driver||'Nie przypisano')}</strong><small>Kierowca</small></div></div><div class="fleet-stats"><div><span>Dzisiaj</span><b>${safeText(f.km||'0 km')}</b></div><div><span>Prędkość</span><b>${safeText(f.speed||'0 km/h')}</b></div><div><span>GPS</span><b>${safeText(f.gpsConnected?f.gps||'Brak danych':'Niepodłączony')}</b></div></div></article>`).join('')}
function syncAssignmentOptions(){const driverSelect=document.querySelector('#transportForm select[name="driver"]'),truckSelect=document.querySelector('#transportForm select[name="truck"]');const driverValue=driverSelect?.value,truckValue=truckSelect?.value;if(driverSelect){driverSelect.innerHTML=`<option>Nie przypisano</option>${drivers.filter(d=>d.status!=='Nieaktywny').map(d=>`<option>${safeText(d.name)}</option>`).join('')}`;if([...driverSelect.options].some(o=>o.value===driverValue))driverSelect.value=driverValue}if(truckSelect){truckSelect.innerHTML=`<option>Nie przypisano</option>${fleet.filter(f=>f.state!=='Nieaktywny').map(f=>`<option>${safeText(f.truck)}</option>`).join('')}`;if([...truckSelect.options].some(o=>o.value===truckValue))truckSelect.value=truckValue}}
function renderFleetManagement(){document.querySelector('#driversCount').textContent=drivers.length;document.querySelector('#vehiclesCount').textContent=fleet.length;document.querySelector('#driversTable').innerHTML=`<div class="management-head"><span>KIEROWCA</span><span>KONTAKT</span><span>PRAWO JAZDY</span><span>STATUS</span><span></span></div>${drivers.map((d,i)=>`<div class="management-row"><div class="entity-cell"><span class="mini-avatar">${initialsSafe(d.name)}</span><section><b>${safeText(d.name)}</b><small>ID: DR-${String(i+1).padStart(3,'0')}</small></section></div><div><b>${safeText(d.phone||'Brak')}</b><small>${safeText(d.email||'Brak e-maila')}</small></div><div><b>${safeText(d.license||'Brak')}</b><small>ważne do ${safeText(d.until||'—')}</small></div><span><i class="entity-status ${d.status==='Nieaktywny'?'off':''}"></i>${safeText(d.status)}</span><button class="more-btn entity-delete" data-kind="driver" data-key="${safeText(d.name)}">Usuń</button></div>`).join('')}`;document.querySelector('#vehiclesTable').innerHTML=`<div class="management-head vehicle-columns"><span>POJAZD</span><span>KIEROWCA</span><span>DANE GPS</span><span>STATUS</span><span></span></div>${fleet.map(f=>`<div class="management-row vehicle-columns"><div class="entity-cell"><span class="vehicle-mini">▰</span><section><b>${safeText(f.truck)}</b><small>${safeText(f.model||'Nie określono')} · ${safeText(f.year||'—')}</small></section></div><div><b>${safeText(f.driver||'Nie przypisano')}</b><small>${f.driver&&f.driver!=='Nie przypisano'?'Przypisany kierowca':'Wymaga przypisania'}</small></div><div><b>${f.gpsConnected?'Oczekuje na synchronizację':'Niepodłączony'}</b><small>${f.gpsConnected?safeText(f.gps||'Brak danych'):'Skonfiguruj integrację'}</small></div><span><i class="entity-status ${f.state==='Nieaktywny'?'off':''}"></i>${safeText(f.state)}</span><button class="more-btn entity-delete" data-kind="vehicle" data-key="${safeText(f.truck)}">Usuń</button></div>`).join('')}`;syncAssignmentOptions()}
function renderFuelFleet(){const body=document.querySelector('#fuelFleetBody');if(!body)return;body.innerHTML=fleet.map(f=>{const level=Number.isFinite(Number(f.fuelLevel))?Number(f.fuelLevel):null,usage=Number.isFinite(Number(f.fuelUsage))?Number(f.fuelUsage):null,low=level!==null&&level<30;return `<tr><td><div class="driver-cell"><span class="vehicle-mini">▰</span><div><strong>${safeText(f.truck)}</strong><small>${safeText(f.driver||'Nie przypisano')}</small></div></div></td><td>${level===null?'<span class="badge amber">Brak odczytu GPS</span>':`<div class="tank-level"><div><i class="${low?'low':''}" style="width:${Math.max(0,Math.min(100,level))}%"></i></div><b>${level}%</b></div>`}</td><td><strong>${level===null?'—':`~${Math.round(level*13.4)} km`}</strong></td><td><strong>${usage===null?'—':`${usage} l/100 km`}</strong></td><td><strong>${usage===null?'—':`${(usage*1.61/100).toFixed(2)} €/km`}</strong></td><td><span class="badge ${low?'red':'amber'}">${low?'Zaplanuj tankowanie':level===null?'Oczekuje na dane':'Poziom OK'}</span></td></tr>`}).join('')||'<tr><td colspan="6"><div class="workspace-empty compact"><b>Brak pojazdów</b><span>Dodaj flotę, aby rozpocząć analizę paliwa.</span></div></td></tr>'}
function openTransport(id){const t=transports.find(item=>item.id===id);if(!t)return;document.querySelector('#drawerContent').innerHTML=`<div class="drawer-header"><span class="eyebrow">${safeText(t.id)}</span><h2>${safeText(t.client)}</h2><p>Transport zapisany w Logistic Master</p></div><span class="badge ${safeText(t.tone||'blue')}">${safeText(t.status||'Nowy')}</span><div class="drawer-route"><div><i></i><section><small>ZAŁADUNEK</small><b>${safeText(t.from)}</b></section></div><span></span><div><i></i><section><small>ROZŁADUNEK</small><b>${safeText(t.to)}</b></section></div></div><div class="drawer-section"><h3>Zasoby</h3><div class="drawer-grid"><div><span>Kierowca</span><b>${safeText(t.driver||'Nie przypisano')}</b></div><div><span>Ciągnik</span><b>${safeText(t.truck||'Nie przypisano')}</b></div><div><span>Naczepa</span><b>${safeText(t.trailer||'Nie przypisano')}</b></div><div><span>Planowane ETA</span><b>${safeText(t.eta||'—')}</b></div></div></div><div class="drawer-section"><h3>Pozycja GPS</h3><p>${safeText(t.gpsLocation||'Brak zsynchronizowanych danych GPS.')}</p></div><button class="primary-btn full" data-report-from-drawer="${safeText(t.id)}">Przygotuj raport dla klienta</button>`;document.querySelector('#detailDrawer').classList.add('open');document.querySelector('#drawerBackdrop').classList.add('open')}
function reportMarkup(t){return `<div class="email-preview"><span class="eyebrow">WERSJA ROBOCZA WIADOMOŚCI</span><label><span>Do:</span><input value="${safeText(t.recipient||'') }" placeholder="E-mail kontrahenta"></label><label><span>Temat:</span><input value="Transport update · ${safeText(t.id)}"></label><div class="email-body" contenteditable="true">Good morning,<br><br>Shipment <strong>${safeText(t.id)}</strong> is planned from ${safeText(t.from)} to ${safeText(t.to)}. Current status: <strong>${safeText(t.status||'New')}</strong>.<br><br>Estimated arrival: <strong>${safeText(t.eta||'to be confirmed')}</strong>.<br><br>Best regards,<br>Logistics Team</div><div class="email-actions"><button class="secondary-btn copy-report">Kopiuj treść</button><button class="primary-btn send-draft">Utwórz draft e-mail</button></div></div>`}
function renderReports(){const root=document.querySelector('#reportsWorkspace');if(!transports.length){root.innerHTML='<div class="workspace-empty"><b>Brak raportów</b><span>Raporty pojawią się po dodaniu pierwszego transportu.</span></div>';return}root.innerHTML=`<div class="report-sidebar">${transports.slice(0,8).map((t,i)=>`<button class="report-select ${i===0?'active':''}" data-report="${safeText(t.id)}"><h4>${safeText(t.client)}</h4><p>${safeText(t.id)} · ${safeText(t.to)}</p><span class="badge amber">Do przygotowania</span></button>`).join('')}</div>${reportMarkup(transports[0])}`;bindReportActions()}
function bindReportActions(){document.querySelectorAll('.report-select').forEach(button=>button.onclick=()=>{const t=transports.find(item=>item.id===button.dataset.report);if(!t)return;document.querySelectorAll('.report-select').forEach(item=>item.classList.toggle('active',item===button));document.querySelector('#reportsWorkspace .email-preview').outerHTML=reportMarkup(t);bindReportActions()});document.querySelector('.copy-report')?.addEventListener('click',async()=>{const text=document.querySelector('.email-body')?.innerText||'';await navigator.clipboard?.writeText(text);showToast('Raport skopiowany','Treść jest gotowa do wklejenia do poczty.')});document.querySelector('.send-draft')?.addEventListener('click',()=>showToast('Integracja e-mail nieaktywna','Po podłączeniu backendu draft zostanie utworzony w skrzynce.'))}
document.addEventListener('click',event=>{const button=event.target.closest('.entity-delete');if(!button)return;event.stopPropagation();const {kind,key}=button.dataset;if(!confirm(`Usunąć: ${key}?`))return;if(kind==='transport')transports=transports.filter(item=>item.id!==key);if(kind==='driver'){drivers=drivers.filter(item=>item.name!==key);fleet.forEach(item=>{if(item.driver===key)item.driver='Nie przypisano'});transports.forEach(item=>{if(item.driver===key)item.driver='Nie przypisano'})}if(kind==='vehicle'){fleet=fleet.filter(item=>item.truck!==key);transports.forEach(item=>{if(item.truck===key)item.truck='Nie przypisano'})}refreshAll();showToast('Element usunięty','Powiązane rekordy zostały bezpiecznie odpięte.')});
document.querySelector('#transportForm').onsubmit=event=>{event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget));if(transports.some(item=>item.id.trim().toLowerCase()===d.number.trim().toLowerCase())){showToast('Taki numer już istnieje','Numer transportu musi być unikalny.');return}activateRealWorkspace();transports.unshift({id:d.number.trim(),client:d.client.trim(),from:d.from.trim(),to:d.to.trim(),driver:d.driver,truck:d.truck,trailer:d.trailer.trim()||'Nie przypisano',notes:d.notes.trim(),progress:0,left:'—',eta:d.date.replace('T',', '),status:'Nowy',tone:'blue'});refreshAll();modal.classList.remove('open');event.currentTarget.reset();showToast('Transport został utworzony',`${d.number} dodano do planera.`)};
document.querySelector('#driverForm').onsubmit=event=>{event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget)),name=`${d.firstName.trim()} ${d.lastName.trim()}`;if(drivers.some(item=>item.name.toLowerCase()===name.toLowerCase())){showToast('Kierowca już istnieje','Sprawdź imię i nazwisko.');return}activateRealWorkspace();drivers.push({name,phone:d.phone.trim(),email:d.email.trim(),license:d.license.trim(),until:d.licenseUntil,status:d.status});refreshAll();driverModal.classList.remove('open');event.currentTarget.reset();showToast('Kierowca został dodany','Możesz przypisać go do nowego transportu.')};
document.querySelector('#vehicleForm').onsubmit=event=>{event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget)),truck=d.truck.trim().toUpperCase();if(fleet.some(item=>item.truck===truck)){showToast('Pojazd już istnieje','Numer rejestracyjny musi być unikalny.');return}if(d.vin.trim().length!==17){showToast('Nieprawidłowy VIN','Numer VIN powinien zawierać 17 znaków.');return}activateRealWorkspace();fleet.push({truck,driver:'Nie przypisano',state:'Dostępny',km:'0 km',speed:'0 km/h',gps:'Brak synchronizacji',gpsConnected:false,model:d.model.trim(),year:d.year,vin:d.vin.trim().toUpperCase(),type:d.type});refreshAll();vehicleModal.classList.remove('open');event.currentTarget.reset();showToast('Pojazd został dodany','Integrację GPS skonfigurujesz w Ustawieniach.')};
document.querySelector('#analyzeEmailBtn').onclick=()=>{const source=document.querySelector('#emailSource').value.trim();if(!source){showToast('Brakuje treści wiadomości','Wklej maila, który mamy przeanalizować.');return}const form=document.querySelector('#transportForm'),id=source.match(/(?:TR|NF|ORDER|ZLECENIE)[\s:#-]*[A-Z0-9/-]{3,}/i)?.[0],route=source.match(/(?:z|from)\s+([^\n,;]+(?:,\s*[A-Z]{2})?).{0,30}(?:do|to)\s+([^\n,;]+(?:,\s*[A-Z]{2})?)/i);if(id)form.elements.number.value=id.replace(/\s+/g,'-').toUpperCase();if(route){form.elements.from.value=route[1].trim();form.elements.to.value=route[2].trim()}form.elements.notes.value=source.slice(0,500);document.querySelector('#extractionResult').classList.add('show');aiPanel.classList.remove('open');showToast('Wstępnie odczytano wiadomość','To lokalny parser. Sprawdź wszystkie pola przed zapisaniem.')};
document.querySelectorAll('.settings-form').forEach((form,index)=>{const section=form.closest('.settings-panel')?.id||`section-${index}`;[...form.elements].forEach((field,i)=>{if(!field.name)field.name=`field_${i}`;const saved=userSettings[section]?.[field.name];if(saved!==undefined){if(field.type==='checkbox')field.checked=Boolean(saved);else if(field.type!=='password')field.value=saved}});form.onsubmit=event=>{event.preventDefault();const values={};[...form.elements].forEach(field=>{if(!field.name||field.type==='submit'||field.type==='button'||field.type==='password')return;values[field.name]=field.type==='checkbox'?field.checked:field.value});userSettings[section]=values;persistSettings();document.querySelector('#settingsSaved').textContent='Zapisano przed chwilą';showToast('Ustawienia zapisane','Konfiguracja tego konta została zapisana lokalnie.')}});
document.querySelectorAll('[data-test-connection],.onboarding-test').forEach(button=>button.onclick=()=>showToast('Potrzebne połączenie z backendem','Test będzie dostępny po zapisaniu danych integracji po stronie serwera.'));
const gpsPanel=document.querySelector('#gpsAppSettings');if(gpsPanel){gpsPanel.querySelector('.connection-badge').className='connection-badge';gpsPanel.querySelector('.connection-badge').textContent='○ Nie skonfigurowano';gpsPanel.querySelectorAll('.connection-summary b')[0].textContent='Brak synchronizacji';gpsPanel.querySelectorAll('.connection-summary b')[1].textContent=`0 / ${fleet.length}`}
if(!demoWorkspace){const integration=document.querySelector('.integration-card');integration?.querySelector('.integration-head small')?.replaceChildren('Niepodłączono');integration?.querySelector('b')?.replaceChildren('Brak synchronizacji');integration?.querySelector('.pulse')?.classList.remove('pulse');const sync=document.querySelector('.sync-chip');if(sync)sync.innerHTML='<i style="background:#f59e42"></i> Dane GPS niepodłączone';const fuelCaption=document.querySelector('.fuel-fleet-panel .panel-heading p');if(fuelCaption)fuelCaption.textContent='Dane z sond paliwowych pojawią się po podłączeniu aplikacji GPS.'}
function renderTimeline(){const root=document.querySelector('#timelineRows');root.innerHTML=fleet.slice(0,4).map(f=>{const job=transports.find(t=>t.truck===f.truck||t.driver===f.driver);return `<div class="timeline-row"><div class="timeline-person"><span class="mini-avatar">${initialsSafe(f.driver)}</span><div><strong>${safeText(f.driver||'Nie przypisano')}</strong><small>${safeText(f.truck)}</small></div></div><div class="timeline-track">${job?`<div class="timeline-job job-blue" style="left:4%;width:${Math.max(18,Math.min(92,Number(job.progress)||35))}%"><b>${safeText(job.from)} → ${safeText(job.to)}</b>${safeText(job.id)}</div>`:'<div class="timeline-empty">Brak przypisanego transportu</div>'}</div></div>`}).join('')||'<div class="workspace-empty compact"><b>Brak zasobów w planerze</b><span>Dodaj pojazdy i kierowców w module floty.</span></div>'}
let scopedStep=Number(localStorage.getItem(userStateKey('onboarding_step'))||0);onboardingStep=scopedStep;
document.querySelector('#openOnboarding').onclick=()=>{onboardingStep=Number(localStorage.getItem(userStateKey('onboarding_step'))||0);showOnboarding()};
document.querySelector('#pauseOnboarding').onclick=()=>{localStorage.setItem(userStateKey('onboarding_step'),onboardingStep);closeOnboarding();showToast('Postęp został zapisany','Wznowisz konfigurację z menu konta.')};
document.querySelector('#onboardingBack').onclick=()=>{if(onboardingStep>0)onboardingStep--;localStorage.setItem(userStateKey('onboarding_step'),onboardingStep);renderOnboarding()};
document.querySelector('#onboardingNext').onclick=()=>{
  if(onboardingStep===1){const name=document.querySelector('#onboardCompany').value.trim();if(!name){showToast('Podaj nazwę firmy','To pole jest wymagane do zakończenia konfiguracji.');return}userSettings.company={name,nip:document.querySelector('#onboardNip').value.trim(),phone:document.querySelector('#onboardPhone').value.trim()};persistSettings()}
  if(onboardingStep===2){const truck=document.querySelector('#onboardTruck').value.trim().toUpperCase();if(!truck){showToast('Dodaj pierwszy pojazd','Numer rejestracyjny jest wymagany.');return}onboardingDraft.vehicle={truck,driver:'Nie przypisano',state:'Dostępny',km:'0 km',speed:'0 km/h',gps:'Brak synchronizacji',gpsConnected:false,model:document.querySelector('#onboardModel').value.trim()||'Nie określono',year:'—'};saveOnboardingDraft()}
  if(onboardingStep===3){const first=document.querySelector('#onboardDriverFirst').value.trim(),last=document.querySelector('#onboardDriverLast').value.trim();if(!first||!last){showToast('Dodaj pierwszego kierowcę','Imię i nazwisko są wymagane.');return}onboardingDraft.driver={name:`${first} ${last}`,phone:document.querySelector('#onboardDriverPhone').value.trim(),email:'',license:document.querySelector('#onboardLicense').value.trim()||'Do uzupełnienia',until:'Do uzupełnienia',status:'Dostępny'};saveOnboardingDraft()}
  if(onboardingStep===6){activateRealWorkspace();if(onboardingDraft.vehicle&&!fleet.some(f=>f.truck===onboardingDraft.vehicle.truck))fleet.push(onboardingDraft.vehicle);if(onboardingDraft.driver&&!drivers.some(d=>d.name===onboardingDraft.driver.name))drivers.push(onboardingDraft.driver);onboardingDraft={};localStorage.removeItem(workspaceKey+'_onboarding_draft');localStorage.setItem(userStateKey('onboarding_complete'),'true');localStorage.removeItem(userStateKey('onboarding_pending'));localStorage.removeItem(userStateKey('onboarding_step'));refreshAll();closeOnboarding();showToast('Konfiguracja podstawowa zakończona','Integracje zewnętrzne nadal wymagają bezpiecznego backendu.');return}
  onboardingStep++;localStorage.setItem(userStateKey('onboarding_step'),onboardingStep);renderOnboarding()
};
loadHardenedUserSession();renderTable();renderCards();renderFleet();renderFleetManagement();renderFuelFleet();renderTimeline();renderReports();renderSafeSummary();updateNotificationCounts();
}

/* Mobile navigation, scroll locking and current date. */
const mobileSidebar=document.querySelector('#sidebar');
const mobileBackdrop=document.querySelector('#mobileNavBackdrop');
function syncMobileScrollLock(){const mobile=window.matchMedia('(max-width: 760px)').matches;const blocking=mobile&&(mobileSidebar?.classList.contains('open')||document.querySelector('.modal-backdrop.open')||document.querySelector('.onboarding-backdrop.open')||document.querySelector('.detail-drawer.open'));document.body.classList.toggle('mobile-lock',Boolean(blocking))}
function closeMobileNavigation(){mobileSidebar?.classList.remove('open');mobileBackdrop?.classList.remove('open');document.querySelector('#mobileMenu')?.setAttribute('aria-expanded','false');syncMobileScrollLock()}
const mobileMenuButton=document.querySelector('#mobileMenu');
if(mobileMenuButton){mobileMenuButton.setAttribute('aria-expanded','false');mobileMenuButton.onclick=()=>{const open=!mobileSidebar.classList.contains('open');mobileSidebar.classList.toggle('open',open);mobileBackdrop?.classList.toggle('open',open);mobileMenuButton.setAttribute('aria-expanded',String(open));syncMobileScrollLock()}}
mobileBackdrop?.addEventListener('click',closeMobileNavigation);
document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',closeMobileNavigation));
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMobileNavigation()});
const mobileStateObserver=new MutationObserver(syncMobileScrollLock);
document.querySelectorAll('.modal-backdrop,.onboarding-backdrop,.detail-drawer').forEach(element=>mobileStateObserver.observe(element,{attributes:true,attributeFilter:['class']}));
window.addEventListener('resize',()=>{if(!window.matchMedia('(max-width: 760px)').matches)closeMobileNavigation();else syncMobileScrollLock()});
const dateLabel=document.querySelector('.topbar-title .eyebrow');
if(dateLabel)dateLabel.textContent=new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();
