const tabs=document.querySelectorAll('[data-auth-tab]');
function showAuth(view){tabs.forEach(t=>t.classList.toggle('active',t.dataset.authTab===view));document.querySelectorAll('.auth-view').forEach(v=>v.classList.remove('active'));document.querySelector(`#${view}Panel`).classList.add('active')}
tabs.forEach(t=>t.onclick=()=>showAuth(t.dataset.authTab));
document.querySelector('[data-switch-register]').onclick=()=>showAuth('register');document.querySelector('[data-switch-login]').onclick=()=>showAuth('login');
document.querySelectorAll('.toggle-password').forEach(btn=>btn.onclick=()=>{const input=btn.parentElement.querySelector('input');input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'◉':'○'});
function saveSession(profile,remember=false){const store=remember?localStorage:sessionStorage;store.setItem('lm_session',JSON.stringify({...profile,authenticatedAt:new Date().toISOString()}));localStorage.setItem('lm_profile',JSON.stringify(profile))}
function saveAccount(profile){const accounts=JSON.parse(localStorage.getItem('lm_accounts')||'[]');const updated=accounts.filter(account=>account.email!==profile.email);updated.push(profile);localStorage.setItem('lm_accounts',JSON.stringify(updated))}
document.querySelector('#registerForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const profile={firstName:data.firstName.trim(),lastName:data.lastName.trim(),email:data.email.trim().toLowerCase(),phone:data.phone.trim(),role:'Dyspozytor'};saveAccount(profile);saveSession(profile,true);localStorage.setItem('lm_onboarding_pending','true');document.querySelectorAll('.auth-view,.auth-tabs').forEach(x=>x.classList.remove('active'));document.querySelector('#authSuccess').classList.add('show');setTimeout(()=>location.href='index.html',1200)};
document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const email=data.email.trim().toLowerCase();const accounts=JSON.parse(localStorage.getItem('lm_accounts')||'[]');const legacy=JSON.parse(localStorage.getItem('lm_profile')||'null');const profile=accounts.find(account=>account.email===email)||(legacy?.email===email?legacy:null);if(!profile){showAuth('register');document.querySelector('#registerForm input[name="email"]').value=email;showToast('Nie znaleźliśmy tego konta','Uzupełnij imię i nazwisko, aby dokończyć rejestrację.');return}saveSession(profile,Boolean(data.remember));const btn=e.currentTarget.querySelector('.auth-submit');btn.textContent='Logowanie…';setTimeout(()=>location.href='index.html',650)};
document.querySelector('.forgot-link').onclick=()=>showToast('Resetowanie hasła','W wersji produkcyjnej wyślemy link na podany e-mail.');
function showToast(title,msg){const t=document.querySelector('#toast');t.querySelector('b').textContent=title;t.querySelector('p').textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
